version: "3"

services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sonarqube:
    image: sonarqube:8.4.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"

volumes:
  mysql_data: